using System.ComponentModel.DataAnnotations.Schema;

namespace Monopoly.API.Data.Entities;

/// <summary>
///     Represents an abstract base class for warehouse objects.
///     This class serves as a foundation for specific types of warehouse items, defining common properties and behaviors.
/// </summary>
public abstract class WarehouseObject
{
    /// <summary>
    ///     Gets or sets the unique identifier for the warehouse object.
    ///     This property is automatically generated by the database upon creation of a new record.
    /// </summary>
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }

    /// <summary>
    ///     Gets or sets the width of the warehouse object in appropriate units (e.g., meters or centimeters).
    /// </summary>
    public decimal Width { get; set; }

    /// <summary>
    ///     Gets or sets the height of the warehouse object in appropriate units (e.g., meters or centimeters).
    /// </summary>
    public decimal Height { get; set; }

    /// <summary>
    ///     Gets or sets the depth of the warehouse object in appropriate units (e.g., meters or centimeters).
    /// </summary>
    public decimal Depth { get; set; }

    /// <summary>
    ///     Gets the globally unique identifier for the warehouse object.
    ///     This GUID is automatically computed by the database and can be used to uniquely identify objects across different
    ///     systems.
    /// </summary>
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public Guid Rowguid { get; set; }

    /// <summary>
    ///     Gets the weight of the warehouse object in appropriate units (e.g., kilograms or pounds).
    ///     This property must be implemented in derived classes.
    /// </summary>
    public virtual decimal Weight { get; }

    /// <summary>
    ///     Gets the volume of the warehouse object, calculated from its dimensions.
    ///     This property must be implemented in derived classes.
    /// </summary>
    public abstract decimal Volume { get; }
}